name: California Housing CML

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Node.js (for CML)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CML CLI
        run: |
          npm install -g @dvcorg/cml

      - name: Train model
        run: python train.py

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create cml_report.md
